// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkcbP-f5IV99IqclZJWE0uw4F6eMuf2Ks',
    appId: '1:989556781175:web:62c62b5f21b1bf61e41672',
    messagingSenderId: '989556781175',
    projectId: 'nura-74502',
    authDomain: 'nura-74502.firebaseapp.com',
    storageBucket: 'nura-74502.appspot.com',
    measurementId: 'G-72F3ZYQG0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfRcUC2wPTq9HT-h7Vm0Aows7XPPSajZA',
    appId: '1:989556781175:android:cd5f16371fe79ccae41672',
    messagingSenderId: '989556781175',
    projectId: 'nura-74502',
    storageBucket: 'nura-74502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0VDqZo8fQvDUYlh5hFkGdkBI9yO61rjY',
    appId: '1:989556781175:ios:0f9ab21c5adf41c2e41672',
    messagingSenderId: '989556781175',
    projectId: 'nura-74502',
    storageBucket: 'nura-74502.appspot.com',
    iosBundleId: 'com.example.shareYourExperience',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0VDqZo8fQvDUYlh5hFkGdkBI9yO61rjY',
    appId: '1:989556781175:ios:0f9ab21c5adf41c2e41672',
    messagingSenderId: '989556781175',
    projectId: 'nura-74502',
    storageBucket: 'nura-74502.appspot.com',
    iosBundleId: 'com.example.shareYourExperience',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkcbP-f5IV99IqclZJWE0uw4F6eMuf2Ks',
    appId: '1:989556781175:web:8092a77ad593118ae41672',
    messagingSenderId: '989556781175',
    projectId: 'nura-74502',
    authDomain: 'nura-74502.firebaseapp.com',
    storageBucket: 'nura-74502.appspot.com',
    measurementId: 'G-7W3QEPL7G9',
  );
}
